var bollywood_movies = ['Target',
 'Bhaji on the Beach ',
 'Children of Heaven  The Bacheha-Ye Aseman ',
 'Bandit Queen ',
 'Asoka Ashoka the Great ',
 'Salaam Bombay! ',
 'War and Peace Jang Aur Aman ',
 'Fire ',
 'Veer Zaara ',
 'Dil Se ',
 'Something Is Happening Kuch Kuch Hota Hai ',
 'Devdas ',
 'Sometimes Happiness  Sometimes Sorrow Kabhi Khushi Kabhie Gham ',
 'D.C.H. Dil Chahta Hai ',
 'Kal Ho Naa Ho ',
 'Bomb the System ',
 'Deceivers  The ',
 'Parineeta ',
 'Sholay ',
 'Hum Dil De Chuke Sanam ',
 'Black ',
 'Main Hoon Na ',
 'Dilwale Dulhania Le Jayenge ',
 'Mother India ',
 'Paheli ',
 'Chess Players  The Shatranj Ke Khilari ',
 'Krrish ',
 'Yuva ',
 'My Bollywood Bride ',
 'Namesake  The ',
 'Eklavya: The Royal Guard ',
 'Paint It Yellow Rang De Basanti ',
 'Om Shanti Om ',
 'Like Stars on Earth Taare Zameen Par ',
 'Jodhaa Akbar ',
 'Saawariya ',
 'Marriage Made in Heaven  A Rab Ne Bana Di Jodi ',
 'Don ',
 'Billu ',
 'Salaam Namaste ',
 'Thirst Pyaasa ',
 'Wanted ',
 'Jab We Met ',
 'Paper Flowers Kaagaz Ke Phool ',
 'Pure One Pakeezah ',
 'Less of Sugar Cheeni Kum ',
 'Guru ',
 'Aaja Nachle ',
 'Swades: We  the People Our Country ',
 ' Idiots ',
 'Hum Tum ',
 'Hero: Love Story of a Spy  The ',
 'Lucky: No Time For Love ',
 'Mohabbatein ',
 'Singh Is Kinng ',
 'My Name is Khan ',
 'Delhi- ',
 'New York ',
 'B.N.B. Bunty Aur Babli ',
 'One  Ka  ',
 'Shakthi: The Power ',
 'Chalte Chalte ',
 'Karan Arjun ',
 'Hum Tumhare Hain Sanam ',
 'Firaaq ',
 'Chhoti Si Baat ',
 'Salaam-E-Ishq ',
 'Chance Pe Dance ',
 'Dhoondte Reh Jaoge ',
 'Aladin ',
 'Accident on Hill Road ',
 'Raincoat ',
 'Amar Akbar Anthony ',
 'Ankur The Seedling ',
 'Pyaar Impossible ',
 'Tere Naam ',
 'Luck by Chance ',
 'Peepli Live ',
 'Tramp  The Awaara Awara ',
 'Karthik Calling Karthik ',
 'Get Educated: Paathshaala ',
 'Chori Chori Chupke Chupke ',
 'Baghban ',
 'Mujhse Shaadi Karogi ',
 'Tere Bin Laden ',
 'Disco Dancer ',
 'Band Baaja Baaraat ',
 'Kaho Naa... Pyaar Hai ',
 'Mujhse Dosti Karoge! ',
 'Main Prem Ki Diwani Hoon ',
 'Ghajini ',
 'Fool N Final ',
 'Hum Aapke Hain Koun...! ',
 'Om Jai Jagadish ',
 'Aankhen ',
 'Seventh Horse of the Sun  Suraj Ka Satvan Ghoda ',
 'Laaga Chunari Mein Daag: Journey of a Woman ',
 'De Dana Dan ',
 'Double Dhamaal ',
 'Delhi Belly ',
 'Zindagi Na Milegi Dobara ',
 'Masti ',
 'Singham ',
 'Chandni Chowk to China ',
 'Ladies vs. Ricky Bahl ',
 'Chak De India! ',
 'Paan Singh Tomar ',
 'Housefull  ',
 'Agent Vinod ',
 'Aakrosh ',
 'Rocket Singh: Salesman of the Year ',
 'Vicky Donor ',
 'Bombay Talkie ',
 'Desi Boyz ',
 'Kahaani ',
 'No Problem ',
 'Householder  The Gharbar ',
 'In Custody ',
 'Ishaqzaade ',
 'Shakespeare-Wallah ',
 'Gangs of Wasseypur ',
 'Student of the Year ',
 'OMG Oh My God! ',
 'Barfi! ',
 ' Khoon Maaf ',
 'Mahakaal The Monster ',
 'English Vinglish ',
 'Dabangg  ',
 'Udaan ',
 'Heroine ',
 'Don ',
 'Hey Ram ',
 'Koi... Mil Gaya ',
 'Pyaar Ka Punchnama ',
 'Aks ',
 'Bhaag Milka Bhaag ',
 'D-Day ',
 'Joker ',
 'Chennai Express ',
 'Table No. ',
 'Grand Masti ',
 'Shanghai ',
 'Kabul Express ',
 'Special  ',
 'Talaash ',
 'Drona ',
 'Being Cyrus ',
 'Race ',
 'Fiancee  The Parineeta ',
 'Dhoom ',
 'Scorching Winds Garm Hava Garam Hawa ',
 'The Lunchbox ',
 'Breakaway Speedy Singhs ',
 'Guru  The ',
 'Yeh Jawaani Hai Deewani ',
 'Don  ',
 'Pardes ',
 'Love Story  ',
 'Highway  ',
 'Kai Po Che! ',
 'Kabhi Haan Kabhi Naa ',
 'Duplicate ',
 'Ra.One ',
 'Gunday ',
 'Goliyon Ki Raasleela Ram-Leela ',
 'Villain  The Ek Villain ',
 'Kites ',
 'Haider ',
 'Zanjeer ',
 'Dil Bole Hadippa! ',
 'Aashiqui  ',
 'Deewaar ',
 "It's a Wonderful Afterlife ",
 'Journey Beyond Three Seas ',
 'Action Jackson ',
 'Loins of Punjab Presents ',
 'PK ',
 'Daar ',
 'Ishq ',
 'Happy New Year ',
 'The Unknown ',
 'Lahore ',
 'Ugly ',
 'Dhobi Ghat ',
 'Raanjhanaa ',
 'Dum Laga Ke Haisha ',
 'Baby ',
 'Filmistaan ',
 'N.H  ',
 'Lage Raho Munna Bhai ',
 'Ship of Theseus ',
 'Doli Saja Ke Rakhna',
 'Vaastav: The Reality ',
 'Sarfarosh ',
 'Court ',
 'Piku ',
 'Ankhon Dekhi ',
 'Gulaal ',
 'Black Friday ',
 'Andaz Apna Apna ',
 'Hera Pheri ',
 'Fugly ',
 'Detective Byomkesh Bakshy ',
 'Badlapur ',
 'Holiday ',
 'Wake Up Sid ',
 'Mission Kashmir ',
 'Lakshya ',
 'Iqbal ',
 'Ghulam ',
 'Rangeela ',
 'Bombay Talkies ',
 'Bhool Bhulaiyaa ',
 'Phir Hera Pheri ',
 'Mohra ',
 'Sarkar Raj ',
 'Ek Ajnabee ',
 'Sarkar ',
 'Hulchul ',
 'Samay: When Time Strikes ',
 ': A Love Story ',
 'Nayak: The Real Hero ',
 'Virasat ',
 'Maqbool ',
 'Jab Tak Hai Jaan ',
 'Mere Brother Ki Dulhan ',
 'I Hate Luv Storys ',
 'Happy Ending ',
 'Tanu Weds Manu ',
 'Madras Cafe ',
 'Hamari Adhuri Kahaani ',
 'B.A. Pass ',
 'Gabbar Is Back ',
 'Bluffmaster! ',
 'Bhoot ',
 'Raat ',
 '',
 'You Must Be Scared ',
 'Darna Mana Hai ',
 'Rockstar ',
 'Rock On!! ',
 'Shiva ',
 'Main Khiladi Tu Anari ',
 'Jungle ',
 'Prahaar: The Final Attack ',
 'Sehar ',
 'Zakhm ',
 'Kaminey ',
 'Company ',
 'Vishwaroopam ',
 'Omkara ',
 'Baadshah ',
 'Koyla ',
 'Shool ',
 'Ghayal ',
 'Golmaal ',
 'Saheb Biwi Aur Gangster ',
 'Gadar: Ek Prem Katha ',
 'Shaitan ',
 'Awara Paagal Deewana ',
 'Mardaani ',
 'Shootout at Lokhandwala ',
 'Josh ',
 'Raakh ',
 'Dhoom  ',
 'Dhoom  ',
 'Ram Gopal Varma Ki Aag ',
 'Shahid ',
 'Siddharth ',
 'Queen ',
 'Bhoothnath Returns ',
 'Ishqiya ',
 'Chandni Bar ',
 'Khosla Ka Ghosla! ',
 'Shabd ',
 'Dil ',
 'Once Upon a Time in Mumbaai ',
 'Three Daughters Teen Kanya ',
 'Hooligan ',
 'Bombay Velvet ',
 'Aalavandhan ',
 'Finding Fanny ',
 'Bajrangi Bhaijaan ',
 'Tanu Weds Manu Returns ',
 'Qissa: The Tale of a Lonely Ghost ',
 'Bhuvan Shome ',
 'Manjhi The Mountain Man ',
 'Fly Away Solo ',
 'Sujata ',
 'Devdas ',
 'Brothers ',
 'Taxi No.   : Nau Do Gyarah ',
 'Death of a Doctor ',
 'Aakrosh ',
 'Drishyam ',
 'Phantom ',
 'Zid ',
 'Agneepath ',
 'Cocktail ',
 'Dor ',
 'Lootera ',
 'Apaharan ',
 'Baazigar ',
 'Sparsh ',
 'The Dirty Picture ',
 'Garam Masala ',
 'Chup Chup Ke ',
 'Dulhe Raja ',
 'Mr. & Mrs. Khiladi ',
 'Silsila ',
 'A Prayer for Rain ',
 'Dharam Sankat Mein ',
 'Chupke Chupke ',
 'Go Goa Gone ',
 'Pyaar Ka Punchnama  ',
 'Delhi Safari ',
 'Matrubhoomi ',
 'Padosan ',
 'Ittefaq',
 'Mera Naam Joker ',
 'Haathi Mere Saathi ',
 'Benaam ',
 'Jadu Tona ',
 'Baton Baton Mein ',
 'Beloved Enemy ',
 'Khubsoorat ',
 'Red Rose ',
 'Saboot ',
 'Naram Garam ',
 'Jaane Bhi Do Yaaro ',
 'Masoom ',
 'Hero ',
 'Rang Birangi ',
 'The Old Temple ',
 'Khamosh ',
 'Arjun ',
 'Chameli Ki Shaadi ',
 'Anubhav ',
 'Karma ',
 'Tahkhana ',
 'Mr India ',
 'Tezaab ',
 'Maalamaal ',
 'Veerana ',
 'Maine Pyar Kiya ',
 'Bandh Darwaza ',
 'Shaitani Ilaaka ',
 'Saajan ',
 ' Days ',
 'Phool Aur Kaante ',
 'Heart ',
 'Jo Jeeta Wohi Sikandar ',
 'Suryavanshi ',
 'Chamatkar ',
 'Aankhen ',
 'Hum Hain Rahi Pyar Ke ',
 'King Uncle ',
 'Khal Nayak ',
 'Waqt Hamara Hai ',
 'Suhaag ',
 'Krantiveer ',
 'Gopi Kishan ',
 'Baazi ',
 'Barsaat ',
 'Takkar ',
 'Sapoot ',
 'Khamoshi: The Musical ',
 'Loafer ',
 'Raja Hindustani ',
 'Jeet ',
 'Agni Sakshi ',
 'Ghatak: Lethal ',
 'Chachi  ',
 'Dil To Pagal Hai ',
 'Bhai ',
 'Judwaa ',
 'Gupt: The Hidden Truth ',
 'Daud ',
 'Aflatoon ',
 'Bade Miyan Chote Miyan ',
 'China Gate ',
 'Pyaar Kiya To Darna Kya ',
 'Soldier ',
 'Taal ',
 'Hum Saath Saath Hain ',
 'Jaanam Samjha Karo ',
 'Dil Kya Kare',
 'Kaun ',
 'Pyaar Koi Khel Nahin ',
 'Hogi Pyar Ki Jeet',
 'Biwi No.  ',
 'Hello Brother ',
 'Kartoos ',
 'Mast ',
 'Kachche Dhaage ',
 'Deewane ',
 'Dhadkan ',
 'Khiladi  ',
 'Kurukshetra ',
 'Mela ',
 'Refugee ',
 'Kya Kehna ',
 'Fiza ',
 'Bicchoo ',
 'Har Dil Jo Pyar Karega... ',
 'Pukar ',
 'Beti No.  ',
 'Khauff ',
 'Jis Desh Mein Ganga Rehta Hai ',
 'Hum To Mohabbat Karega ',
 'Badal ',
 'Prem Ratan Dhan Payo ',
 'Chashme Buddoor ',
 'Tamasha ',
 'Talvar ',
 'Pestonjee ',
 'Mary Kom ',
 'The Legend of Bhagat Singh ',
 'Bajirao Mastani ',
 'Namastey London ',
 'Dilwale ',
 'Guzaarish ',
 'Raavan ',
 'Paa ',
 'Khoobsurat ',
 'Bang Bang ',
 'Airlift ',
 'Fitoor ',
 'Daawat-e-Ishq ',
 'Water ',
 'X: Past Is Present ',
 'Ajnabee ',
 'Jodi No. ',
 'Pyaar Tune Kya Kiya',
 'Style ',
 'Love Ke Liye Kuch Bhi Karega ',
 'Mujhe Kucch Kehna Hai ',
 'Albela ',
 'Yaadein ',
 'Indian ',
 'Tum Bin ',
 'Aashiq ',
 'Yeh Raaste Hain Pyaar Ke ',
 'Aamdani Atthanni Kharcha Rupaiya ',
 'Titli ',
 'Anjaana Anjaani ',
 'Neerja ',
 'Agnivarsha: The Fire and the Rain ',
 'Humraaz ',
 'Aap Mujhe Achche Lagne Lage ',
 'road ',
 'Sur ',
 'EK Chotti Si Love Story ',
 'Hum Kisi Se Kum Nahin ',
 'Na Tum Jaano Na Hum ',
 'Makdee ',
 'Deewangee ',
 'Raaz ',
 'Jaani Dushman: Ek Anokhi Kahani ',
 'Maine Dil Tujhko Diya ',
 'Saathiya ',
 'Kaante ',
 'The Cook ',
 'Hisss ',
 'Traffic Signal ',
 'Bhagam Bhag ',
 'Mastizaade ',
 'Main Madhuri Dixit Banna Chahti Hoon!',
 'Jaal: The Trap ',
 'Calcutta Mail ',
 'Dhund: The Fog',
 'Chura Liyaa Hai Tumne ',
 'Saaya ',
 'Qayamat: City Under Threat ',
 'Khel ',
 'LOC: Kargil ',
 'Hawa ',
 'Ishq Vishk ',
 'Khushi ',
 'Zameen ',
 'Sin ',
 'Gangaajal ',
 'Murder ',
 'Khakee ',
 'Fida ',
 'Madhoshi ',
 'Krishna Cottage ',
 'Kismat ',
 'Garv: Pride and Honour ',
 'Rudraksh ',
 'Vaastu Shastra',
 "Deewaar: Let's Bring Our Heroes Home ",
 'Asambhav ',
 'Ek Hasina Thi ',
 'Bardaasht ',
 'Lakeer - Forbidden Lines ',
 'Taarzan: The Wonder Car ',
 'Plan ',
 'Dil Ne Jise Apna Kahaa ',
 'Rakht ',
 'Run ',
 'Kaal ',
 'Deewane Huye Paagal ',
 'Kyaa Kool Hai Hum ',
 'No Entry ',
 'Bose: The Forgotten Hero ',
 'Maine Pyaar Kyun Kiya ',
 'Vaah! Life Ho Toh Aisi! ',
 'Naina ',
 'Kalyug ',
 'Shikhar ',
 'Chocolate: Deep Dark Secrets ',
 'Kyon Ki... ',
 'Karam ',
 'Tango Charlie ',
 'Aashiq Banaya Aapne ',
 'Waqt: The Race Against Time ',
 'Zeher ',
 'Socha Na tha ',
 'Dus ',
 'D ',
 'Elaan ',
 'Page  ',
 'Chaahat Ek Nasha... ',
 'Silent Waters ',
 'Gangster ',
 'Bhoot Unkle ',
 'Naksha ',
 'Woh Lamhe ',
 'Fight Club: Members Only ',
 'Pyaar Ke Side Effects ',
 'Malamaal Weekly ',
 ' China Town ',
 'Corporate ',
 'Tom  Dick And Harry ',
 'Shiva ',
 'Jaane Hoga Kya ',
 'Welcome ',
 'No Smoking ',
 'Dil Dosti Etc ',
 'Dus Kahaniyaan ',
 'The Train: Some Lines Shoulder Never Be Crossed... ',
 'Awarapan ',
 'Good Boy  Bad Boy ',
 'Bheja Fry ',
 'MP: Mera Pehla Pehla Pyaar ',
 'Dhol ',
 'Bachna Ae Haseeno ',
 'Fashion ',
 'Camaraderie ',
 'Krazzy  ',
 'Bhoothnath ',
 'Halla Bol ',
 'Golmaal Returns ',
 'Jannat ',
 'Tashan ',
 'Karzzzz ',
 'Y.M.I. - Yeh Mera India ',
 'The Stoneman Murders ',
 'All The Best ',
 'Kisna ',
 'Dabangg ',
 'Khatta Meetha ',
 'Kaalo ',
 'Shor in the City ',
 'No One Killed Jessica ',
 'Bodyguard ',
 'Thank You ',
 ': Error Not Found ',
 ': Evil Returns ',
 'Ghost ',
 'Aligarh ',
 'Commando - A One Man Army ',
 'Boss ',
 'Jolly LLB ',
 'Shuddh Desi Romance ',
 'Ek Thi Daayan ',
 'Singham Returns ',
 'Raja Natwarlal ',
 'Dedh Ishqiya ',
 'Sulemani Keeda ',
 'Darr @ the Mall ',
 "She Smiles  She's Snared! ",
 ' States ',
 'Heropanti ',
 'Roar ',
 'Creature ',
 'Hunterrr ',
 'Hate Story  ',
 'Holi ',
 'Roja ',
 'Dil Dhadakne Do ',
 'Jackpot ',
 'Force ',
 'Irudhi Suttru ',
 'Raghu Romeo ',
 'Angry Indian Goddesses ',
 'Hate Story ',
 'Hate Story  ',
 'Yakeen ',
 'Fan ',
 'Ardh Satya ',
 'Ghayal Once Again ',
 'Ajab Prem Ki Ghazab Kahani ',
 'Kick ',
 'Teri Meri Kahaani ',
 'Aitraaz ',
 'Singh is Bling ',
 'Jai Gangaajal ',
 'Gulaab Gang ',
 'Umrika ',
 'Azhar ',
 'Kapoor and Sons ',
 'Aarakshan ',
 'Chakravyuh ',
 'Dasvidaniya ',
 'Do Dooni Chaar ',
 'Dum Maaro Dum ',
 'Udta Punjab ',
 'Ten ',
 'Ghanchakkar ',
 'Khichdi: The Movie ',
 'Love Sex aur Dhokha ',
 'Mirch ',
 'Miss Lovely ',
 'Oye Lucky! Lucky Oye! ',
 'Phas Gaye Re Obama ',
 'Saheb Biwi Aur Gangster Returns ',
 'Shamitabh ',
 "Stanley's Tiffin Box ",
 'Tere Naal Love Ho Gaya ',
 'Raman Raghav . ',
 'Sultan ',
 'Nil Battey Sannata ',
 'Kismat Konnection ',
 'Brahman Naman ',
 'Madaari ',
 'Rustom ',
 'Baaghi ',
 'Dishoom ',
 'Ki and Ka ',
 'Mohenjo Daro ',
 'Matru Ki Bijlee Ka Mandola ',
 'Race  ',
 'Hattrick ',
 'Dhamaal ',
 'Himmatwala ',
 'Tees Maar Khan ',
 'Rascals ',
 'God Tussi Great Ho ',
 'Housefull ',
 'Murder  ',
 'Murder  ',
 'Rainbow ',
 'Colors of Passion ',
 'Freaky Ali ',
 'Naughty @  ',
 'Ae Dil Hai Mushkil ',
 'Happy Bhag Jayegi ',
 'Rock On  ',
 'Army ',
 'Dear Zindagi ',
 'Dangal ',
 'Sahib Bibi Aur Ghulam ',
 'Rangoon ',
 'Buddha in a Traffic Jam ',
 'Margarita  with a Straw ',
 'Mughal-E-Azam ',
 'Ok Jaanu ',
 'Pink ',
 'Chittagong ',
 'Parched ',
 'Kaabil ',
 'A Flying Jatt ',
 "Viceroy's House ",
 'Horror Story ',
 'Kabhi Alvida Naa Kehna ',
 'Munna bhai M.B.B.S. ',
 'Kill Dil ',
 'Badrinath Ki Dulhania ',
 'Fanaa ',
 'Shree  ',
 'Tubelight ',
 'Aiyyaa ',
 'Welcome to Sajjanpur ',
 ' A.M ',
 'Kyaa Super Kool Hain Hum ',
 'Phillauri ',
 'Mom ',
 'Jab Harry met Sejal ',
 'Lipstick Under My Burkha ',
 'Hindi Medium ',
 'Mujhse Fraaandship Karoge ',
 'Anand ',
 'Umrao Jaan ',
 'Kuch Naa Kaho ',
 'Jai Ho ',
 'Baar Baar Dekho ',
 'Half Ticket ',
 'The Deliverance ',
 'Newton ',
 'Chef ',
 'Secret Superstar ',
 'Meri Pyaari Bindu ',
 'Hotel Salvation ',
 'Armaan ',
 'Dum ',
 'Phool Aur Patthar ',
 'Satya ',
 'Youngistaan ',
 'Dulhan Hum Le Jayenge ',
 'Tumhari Sulu ',
 'Zubeidaa ',
 'Toilet - Ek Prem Katha ',
 'Gol Maal ',
 'Frangi',
 'Lagaan: Once Upon a Time in India ',
 'Zokkomon ',
 'Judwaa  ',
 'Golmaal Again ',
 'Action Replayy ',
 'Trapped ',
 'Fukrey ',
 'Fukrey Returns ',
 'Om-Dar-Ba-Dar ',
 'Dil Hai Tumhaara ',
 'M.S. Dhoni: The Untold Story ',
 'Padmaavat ',
 'Raees ',
 'Humpty Sharma Ki Dulhania ',
 'Main Tera Hero ',
 'Any Body Can Dance  ',
 'Mr. X ',
 'Ungli ',
 'Raaz: The Mystery Continues... ',
 'Shaadi Mein Zaroor Aana ',
 'Bareilly Ki Barfi ',
 'Behen Hogi Teri ',
 'Raabta ',
 'Break Ke Baad ',
 'Love Aaj Kal ',
 'Heyy Babyy ',
 "What's Your Raashee? ",
 'Tiger Zinda Hai ',
 'Jagga Jasoos ',
 'Ek Tha Tiger ',
 'Qarib Qarib Singlle ',
 'Pushpak ',
 'Aiyaary ',
 'Love Per Square Foot ',
 'Simran ',
 'Sachin: A Billion Dreams ',
 'Sonu Ke Titu Ki Sweety ',
 'Shubh Mangal Saavdhan ',
 'City Lights ',
 'Heroes ',
 'Taxi Driver ',
 'Trimurti ',
 'Raid ',
 'Bobby Jasoos ',
 'Hichki ',
 'A Gentleman ',
 'Johnny Gaddaar ',
 'Daddy ',
 'Mukkabaaz ',
 'Lajja ',
 'Chamku ',
 "Dude  Where's the Party? ",
 'Commando ',
 'Hate Story IV ',
 'Revolver Rani ',
 'U Me Aur Hum ',
 'Race  ',
 'Sanju ',
 'Baaghi  ',
 'Rocky Handsome ',
 'Parmanu: The Story of Pokhran ',
 'Phata Poster Nikhla Hero ',
 'Force  ',
 'Dhadak ',
 'Ramaiya Vastavaiya ',
 'Wajah Tum Ho ',
 'Stree ',
 'Satyameva Jayate ',
 'Manto ',
 'Raazi ']
    let answer = '';
    let maxWrong = 6;
    let mistakes = 0;
    let guessed = [];
    let wordStatus = null;
    
    function randomWord() {
      answer = bollywood_movies[Math.floor(Math.random() * bollywood_movies.length)];
      answer = answer.toUpperCase();
      // console.log(answer.length);
    }
    
    function generateButtons() {
      let buttonsHTML = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'.split('').map(letter =>
        `
          <button
            class="btn btn-lg btn-secondary m-1"
            id='` + letter + `'
            onClick="handleGuess('` + letter + `')"
          >
            ` + letter + `
          </button>
        `).join('');
    
      document.getElementById('keyboard').innerHTML = buttonsHTML;
    }
    
    function handleGuess(chosenLetter) {
      guessed.indexOf(chosenLetter) === -1 ? guessed.push(chosenLetter) : null;
      document.getElementById(chosenLetter).setAttribute('disabled', true);
    
      if (answer.indexOf(chosenLetter) >= 0) {
        guessedWord();
        checkIfGameWon();
      } else if (answer.indexOf(chosenLetter) === -1) {
        mistakes++;
        updateMistakes();
        checkIfGameLost();
        updateHangmanPicture();
      }
    }
    
    function updateHangmanPicture() {
      document.getElementById('hangmanPic').src = './images/' + mistakes + '.jpg';
    }
    
    function checkIfGameWon() {
      if (wordStatus.length === answer.length) {
        document.getElementById('keyboard').innerHTML = 'You Won!!!';
      }
    }
    
    function checkIfGameLost() {
      if (mistakes === maxWrong) {
        document.getElementById('wordSpotlight').innerHTML = 'The answer was: ' + answer;
        document.getElementById('keyboard').innerHTML = 'You Lost!!!';
      }
    }
    
    function guessedWord() {
      wordStatus = answer.split('').map(letter => (guessed.indexOf(letter) >= 0 ? letter : ((letter == ':')?':':((letter == '.')?'.':((letter == '-')?'-':((letter == ' ')?'\xa0':" _ ")))))).join('');
      // console.log(wordStatus.length);
      document.getElementById('wordSpotlight').innerHTML = wordStatus;
    }
    
    function updateMistakes() {
      document.getElementById('mistakes').innerHTML = mistakes;
    }
    
    function reset() {
      mistakes = 0;
      guessed = [];
      document.getElementById('hangmanPic').src = './images/0.jpg';
    
      randomWord();
      guessedWord();
      updateMistakes();
      generateButtons();
    }
    
    document.getElementById('maxWrong').innerHTML = maxWrong;
    
    randomWord();
    generateButtons();
    guessedWord();
    