var tollywood_movies = ['Theliyadhu',
'L-Board',
'Andari Bhanduvayya',
'Okka Kshanam',
'Joru',
'Hasini',
'My Name Is Amrutha',
'Police Police',
'Madhanudu',
'Prasthanam',
'1940 Lo Oka Gramam',
'Darling',
'Buridi',
'Glamour',
'Simha',
'Mouna Ragam',
'Vankaya Fry',
'Daggaraga Dooranga',
'Madatha Kaja',
'Dookudu',
'Vara Prasad Potti Prasad',
'Aakasame Haddu',
'Money Money, More Money',
'Oosaravelli',
'Kandireega',
'Mugguru',
'Dhada',
'Sanchalanam',
'Kodipunju',
'Virodhi',
'Pilla Zamindar',
'Brammigadi Katha',
'Keratam',
'Nuvvila',
'Anthima Theerpu',
'Oh My Friend',
'Nagaram Nidrapotunna Vela',
'Shishira',
'Vachadu Gelichadu',
'Simha Mukhi',
'Markandeyan',
'Kanchana',
'Lankeshwari',
'Gang War',
'Kshetram',
'Rajanna',
'Priyudu',
'Panjaa',
'Bejawada',
'Solo',
'Veedu Theda',
'Sri Rama Rajyam',
'Its My Love Story',
' Mogudu',
'Badrinath',
'Karalu Miriyalu',
'Prema Sagaram',
'Kudirithe Cup Coffee',
'LBW Life Before Wedding',
'Aha Naa Pellanta',
'Katha Screenplay Darshakatvam Appalaraju',
'Vastadu Naa Raju',
'Gaganam',
'Babloo',
'Jai Bolo Telangana',
'Rakshana',
'Vaareva',
'Wanted',
'Ala Modalaindi',
'Golconda High School',
'Anagananga Oka Dheerudu',
'Mirapakaya',
'Parama Veera Chakra',
'Graduate',
'Prema Kavali',
'Mangala',
'Koffee Bar',
'Nitya Pellikoduku',
'Thimmaraju',
'Vykuntapali',
'Dussasana',
'Veera',
'Seema Tapakai',
'100% Love',
'Nenu Naa Rakshasi',
'Mr. Perfect',
'Maaro',
'Teenmaar',
'Lokame Kothaga',
'Manchivadu',
'Shakti',
'Chattam',
'Raaj',
'Dongala Mutha',
'Galli Kurrolu',
"People's War",
'Vennela 1 1/2',
'Avunu',
'Em Babu Laddu Kavala',
'Sorry Teacher',
'Sri Vasavi Vaibhavam',
'Routine Love Story',
'Mythri',
'Kittigadu',
'Chaduvukovali',
'Swati I Love You',
'Yamaho Yama: In America',
'Midhunam',
'Agnatham',
'Genius',
'Onamalu',
'Chanakyudu',
'Maa Abbai Engineering Student',
'Veerangam',
'Yadartha Prema Katha',
'Gandharvulu',
'20th',
'Love Cheste',
'Rushi',
'Shiva Manasulo Shruti',
'Nippu',
'My Heart is Beating',
'Prema Pilustondi',
'Ee Rojullo',
'Seeta Weds Sriram',
'Balaraju Aadi Bammardi',
'Devasthanam',
'Friendsbook',
'Nuvvekadunte Nenakkadunta',
'Maa Oorilo Okasari Emi Jarigindante',
'Ding Dong Bell',
'Break Up',
'Nirbhaya Bharatham',
'Naa Sami Ranga',
'Telisi Teliyaka',
'Waiting for You',
'Athadu Aame O Scooter',
'Music Magic',
'Kamina',
'Sahasra',
'Second Hand',
'Chandee',
'Nenemâ€¦Chinna Pillana?',
'Kaali Charan',
'Entha Andanga Unnave',
'Ishta Sakhi',
'Natho Nenu',
'Pranaya Veedhullo',
'Adda',
'Dhoom 3',
'Gatham',
'Dalam',
'Uyyala Jampala',
'Abbayi Class Ammayi Mass',
'Pusthakamlo Konni Pageelu Missing',
'4th',
'Bullabbai',
'Race',
'Mahankali',
'Backbench Student',
'Rai Rai',
'Swamy Satyananda',
'Priyathama Neevachata Kushalama',
'Jaffa',
'Telugabbai',
'Gouravam',
'Love Touch',
'Chemistry',
'Theatre Lo Naluguru',
'Moksha',
'Oh My Love',
'Operation Dhuryodhana 2',
'Pelli Pustakam',
'Vasool Raja',
'Kevvu Keka',
'Anukshanam',
'Aagadu',
'Loukyam',
'Govindudu Andarivadele',
'Current Theega',
'Dikkulu Choodaku Ramayya',
'Oka Laila Kosam',
'Karthikeya',
'Jai Hind 2',
'Boy Friend Leni Ammayi Unda',
'Paathasala',
'Power',
'Galipatam',
'Ganpati Bappa Morya',
'Boochamma Boochodu',
'Rabhasa',
'Kiraak',
'Nee Jathaga Nenundali',
'Lovers',
'Geethanjali',
'Janmasthanam',
'Nuvvala Nenila',
'Brother of Bommali',
'Chatting',
'Gallo Telinattunde',
'Maaya',
'Raj Mahal',
'Joru',
'Rough',
'Poga',
'Adavi Kachina Vennela',
'',
'15-Aug',
'20-Jun',
'21-Mar',
'14-Mar',
'21-Feb',
'Chinnadana Nee Kosam',
'Mukunda',
'O Manishi Katha',
'Panchabhoothalu Sakshiga',
'Saheba Subramanyam',
'Parampara',
'Ee Varsham Sakshiga',
'The End',
'Lakshmi Raave Maa Intiki',
'Chakkiligintha',
'Ala Ela',
'Yamaleela 2',
'33 Prema Kathalu',
'Naa Bangaaru Talli',
'Rowdy Fellow',
'Ice Cream 2',
'Atreya',
'Pilla Nuvvu Leni Jeevitham',
'Erra Bus',
'Vundile Manchi Kalam Mundu Mundura',
'Run Raja Run',
'Eduruleni Alexander',
' Ice Cream',
'Boy Meets Girl Tholiprema Katha',
'Legend',
'Savior',
'Veta',
'Hrudayam Ekkadunnadi',
'Kamalatho Na Prayanam',
'Yuddham',
'To Let 4 Bachelors Only',
'Nuvve Naa Bangaram',
'Bangaru Kodipetta',
'Bhimavaram Bullodu',
'Alibaba Okkade Donga',
'Special Class',
'Naa Rakumarudu',
'Hum Tum',
'Dil Deewana',
'Malligadu Marriage Bureau',
'Paisa',
'Pandavulu Pandavulu Tummeda',
'Heart Attack',
'Manasunu Maaya Cheyake',
'Yevadu',
'1: Nenokkadine',
'Kshatriya',
'Celebrity',
'Alludu Seenu',
'Love Dot Com',
'Rowdy',
'Medaram Jathara',
'Hrudaya Kaleyam',
'Vichakshana',
'Aa Aiduguru',
'Ra Ra Krishnayya ',
'Inka Emi Anukoleduu',
'Autonagar Surya',
'Oohalu Gusagusalade',
'Jabilli Kosam Akasamalle',
'Jump Jilani',
'Veedu Chaala Worst',
'Ulavacharu Biryani',
'Prema Geema Jantha Nai',
'Manam',
'Pyar Mein Padipoyane',
'Maine Pyaar Kiya',
'Hrudaya Kaleyam (Re-released)',
'April Fool',
'Laddu Babu',
'Drushyam',
'Race Gurram',
'Prathighatana',
'Prabhanjanam',
'Avatharam',
'Prathinidhi',
'Galata',
'Anaamika',
'Kotha Janta',
'Chandamama Kathalu',
'Courier Boy Kalyan',
'Subramanyam For Sale',
'Bale Bale Magadivoy',
'Dynamite',
'Best Actors',
'Kick 2',
'Srimanthudu',
'James Bond',
'Baahubali: The Beginning',
'Tippu',
'Tiger',
'Jadoogadu',
'Vinavayya Ramayya',
'Krishnamma Kalipindi Iddarini',
'Kerintha',
'Lava Kusa',
'Chandrika',
'Jyothi Lakshmi',
'Where is Vidya Balan',
'Shivam',
'Shankarabharanam',
'Bruce Lee',
'Jathakalisey',
'Singham 123',
'Mama Manchu Alludu Kanchu',
'Bhale Manchi Roju',
'Soukhyam',
'Loafer',
'Anaganaga Oka Chitram',
'Hitudu',
'Bengal Tiger',
'Rudhramadevi',
'Veediki Dookudekkuva',
'Size Zero',
'Cheekati Rajyam',
'Kumari 21F',
'Akhil',
'Tripura',
'Sher',
'Raju Gari Gadhi',
'Columbus',
'Kanche',
'Thanu Nenu',
'Asura',
'Mosagallaku Mosagadu (2015 film)',
'Pandaga Chesko',
'Ramleela',
'Bham Bolenath',
'Gayakudu',
'Nuvvu Nenu Okatavudaam',
'Bandipotu',
'Paddanandi Premalo Mari',
'Temper',
'Pesarattu',
'Malli Malli Idi Rani Roju',
'Gaddam Gang',
'Ladies & Gentleman',
'Top Rankers',
'Intelligent Idiots',
'Beeruva',
'Pataas',
'Gopala Gopala',
'Mana Kurralle',
'A Shyam Gopal Varma Film',
'Andhra Pori',
'Surya vs Surya',
'Naakaithe Nachindi',
'Dorakadu',
'Tommy',
'365 Days',
'Anandam Malli Modalaindi',
'Dhee Ante Dhee',
'Lion',
'Dagudumootha Dandakor',
'Rajahmundry ki 50Â\xa0km duramloo',
'Dohchay',
'Kai Raja Kai',
'Varadhi',
'Dongaata',
'S/O Satyamurthy',
'Avunu 2',
'Jil',
'Rey',
'Janda Pai Kapiraju',
'Yevade Subramanyam',
'Tungabhadra',
'Budugu',
'Calling Bell',
'Thappatadugu',
'Jaguar',
'Banthi Poola Janaki',
'Avasaraniko Abaddam',
'Janatha Garage',
'Jo Achyutananda',
'Majnu',
'Siddhartha',
'Hyper',
'Chuttalabbayi',
'Nirmala Convent',
'Aatadukundam Raa',
'Iddaram',
'Bommala Ramaram',
'Babu Bangaram',
'Srirastu Subhamastu',
'Manamantha',
'Jakkanna',
'Pellichoopulu',
'Nayaki',
'Selfie Raja',
'Rojulu Marayi',
'Arddhanaari',
'Abhinetri',
'Thikka',
'Eedu Gold Ehe',
'Pittagoda',
'Premam',
'Kundanapu Bomma',
'Intlo Deyyam Nakem Bhayam',
'Karam Dosa',
'Appatlo Okadundevadu',
'Sarabha',
'Vangaveeti',
'Sapthagiri Express',
'Naanna Nenu Naa Boyfriends',
'Janaki Ramudu',
'Nenosta',
'Dhruva',
'Araku Road Lo',
'Jayammu Nischayammu Raa',
'Ekkadiki Pothavu Chinnavada',
'Sahasam Swasaga Sagipo',
'Naruda Donoruda',
'Manalo Okkadu',
'Aavu Puli Madhyalo Prabhas Pelli',
'Thanu Vachenanta',
'Shankara',
'Nandini Nursing Home',
'L7',
'Ism',
'Mana Oori Ramayanam',
'Oka Manasu',
'Meelo Evaru Koteeswarudu',
'Premikudu',
'Kalyana Vaibhogame',
'Guntur Talkies',
'Veeri Veeri Gu',
'Terror',
'Padesave',
'Eluka Majaka',
'Kshanam',
'Malupu',
'Krishnashtami',
'Garam',
'Krishna Gadi Veera Prema Gaadha',
'Vennello Hai Hai',
'Speedunnodu',
'Lajja',
'Seethamma Andalu Ramayya Sitralu',
'Lacchimdeviki O Lekkundi',
'Soggade Chinni Nayana',
'Dictator',
'Express Raja',
'Nenu Sailaja',
'Abbayitho Ammayi',
'Chitram Bhalare Vichitram',
'Meeku Meere Maaku Meme',
'Shourya',
'Tuntari',
'Nannaku Prematho',
'O Sthree Repu Raa',
'Tulasi Dalam',
'Gentleman',
'Right Right',
'A Aa',
'Brahmotsavam',
'Supreme',
'Raja Cheyyi Vesthe',
'Sarrainodu',
'Eedo Rakam Aado Rakam',
'Sardaar Gabbar Singh',
'Savitri',
'Okka Ammayi Thappa',
'7 To 4',
'Attack',
'Drishya Kavyam',
'Dandakaranyam',
'Romance With Finance',
'Seesa',
'Oopiri',
'Mohabbat Mein',
'Ammayi Aaruguru',
'Meera',
'Run',
'Nenu Maa College',
'Vunnadhi Okate Zindagi',
'Angel',
'Lovers Club',
'Next Nuvve',
'PSV Garuda Vega',
'C/o Surya',
'Okkadu Migiladu',
'Dare',
'London Babulu',
'Baby',
'Prematho Mee Karthik',
'Snehamera Jeevitham',
'Napoleon',
'Balakrishnudu',
'Devi Sri Prasad',
'Jandhyala Rasina Premakatha',
'Dyavudaa',
'June 1:43',
'Prema Entha Madhuram Priyuralu Antha Katinam',
'Anaganaga Oka Durga',
'SriValli',
'Yours Lovingly',
'Mental Madhilo',
'VIP 2',
'Nee Preme Naa Pranam',
'Paisa Vasool',
'Shalini',
'Vellipomaakey',
'Meda Meeda Abbayi',
'Yuddham Sharanam',
'Kathalo Rajakumari',
'Veedevadu',
'Jai Lava Kusa',
'Spyder',
'Mahanubhavudu',
'Lavanya With Love Boys',
'Bava Maradallu',
'Nenu Kidnap Ayyanu',
'Oye Ninne',
'Gulf',
'Raju Gari Gadhi 2',
'Raja The Great',
'Oxygen',
'Nagaram',
'Sapthagiri LLB',
'Arjun Reddy',
'100% Break Up',
'Poorna',
'Enthavaraku Ee Prema',
'Mande Suryudu',
'Sivalinga',
'Pisachi 2',
'Sachin: A Billion Dreams',
'Kong: Skull Island',
'Marakathamani',
'Spider-Man: Homecoming',
'21-Jul',
'Team 5',
'The Foreigner',
'Geostorm',
'Julie 2',
'15-Dec',
'Project Z',
'Mom',
'Logan',
'Guardians The Superheroes',
'Resident Evil: The Final Chapter',
'B.Tech Babulu',
'Malli Raava',
'Premika',
'Vanavillu',
'Kiss Kiss Bang Bang',
'Idhi Maa Prema Katha',
'Juliet Lover of Idiot',
'Kutumba Katha Chitram',
'Lacchi',
'Mama O Chandamama',
'Padipoya Nee Mayalo',
'Seetha...Ramuni Kosam',
'Tholi Parichayam',
'Undha Ledha',
'MCA (Middle Class Abbayi)',
'E Ee',
'Hello',
'Okka Kshanam',
'2 Countries',
'Jawaan',
'Preminche Panilo Vunna',
'Ungarala Rambabu',
'Anando Brahma',
'Happy Birthday',
'Maa Abbayi',
'Nenorakam',
'Pichiga Nachav',
'Katamarayudu',
'Kannayya',
'Nuvvu Evaro Nenu Evaro',
'Cine Mahal - Rojuki 4 Aatalu',
'Guru',
'Rogue',
'Aranyamlo',
'Chinni Chinni Asalu Nalo Regene',
'Kathrina Kareena Madyalo Kamalhaasan',
'Lakshmi Devi Samarpinchu Nede Chudandi',
'Nuvvu Nenu Osey Orey',
'Saranam Gacchami',
' Mister',
'Dhada Puttistha',
'Iddari Madhya 18',
'Lakshmi Bomb',
'Lanka',
'Chitrangada',
'Kittu Unnadu Jagratha',
'Evaro Tanevaro',
'Inkenti Nuvve Cheppu',
'No.1 Hero Rajendar Love Stori',
'Padamati Sandhyaragam London Lo',
'Ye Rojaithey Chusaano',
'Khaidi No. 150',
'Prathi Kshanam',
'Head Constable Venkataramaiah',
'Shatamanam Bhavati',
'Luckunnodu',
'Nenu Local',
'Ika..Se..Love',
'Om Namo Venkatesaya',
' Ghazi',
'Vajralu Kavala Nayana',
'C/o Godavari',
'Winner',
'Dwaraka',
'Gunturodu',
'Aakatayi',
'Lover Boy',
'Gautamiputra Satakarni',
'Babu Baga Busy',
'Rendu Rellu Aaru',
'Dr. Chakravarthy',
'Patel S. I. R.',
'Shamanthakamani',
'Fidaa',
'Kala Varam Aaye',
'Maya Mall',
'Vaisakham',
'Rakshasi',
'Goutham Nanda',
'Darsakudu',
'Green Card',
'Idem Deyyam',
'Nakshatram',
'LIE',
'Jaya Janaki Nayaka',
'Nene Raju Nene Mantri',
'Baahubali: The Conclusion',
'Naku Nene Thopu Turumu',
'Ninnu Kori',
'Vasham',
'Jayadev',
'Khayyum Bhai',
'Rakshaka Bhatudu',
'Venkatapuram',
'Mixture Potlam',
'Tik Tak',
'Gopyam',
'Neelimalai',
'O Pilla Nee Valla',
'Rarandoi Veduka Chudham',
'Keshava',
'Sriramudinta Srikrishnudanta',
'Duvvada Jagannadham',
'Raja Meeru Keka',
'Pelliki Mundu Prema Katha',
'Kaadhali',
'Radha',
'Neelampati Ammoru',
'Fashion Designer s/o Ladies Tailor',
'Ami Thumi',
'Andhhagadu',
'Kathanayakulu',
'Devadas',
'Natakam',
'Desamlo Dongalu Paddaru',
'Bhale Manchi Chowka Beram',
'NOTA',
'Aravinda Sametha Veera Raghava',
'Moodu Puvulu Aaru Kayalu',
'Hello Guru Prema Kosame',
'Bangari Balaraju',
'Savyasachi',
'Ratham',
'Veera Bhoga Vasantha Rayalu',
'Desa Dimmari',
'Nannu Dochukunduvate',
'2 Friends',
'Maari 2',
'C/O Kancharapalem',
'Ee Maya Peremito',
'Aatagallu',
'Adhugo',
'Anthaku Minchi',
'Neevevaro',
'Super Sketch',
'@Nartanasala',
'Paper Boy',
'Antharvedham',
'Sameeram',
'Manu',
'Premaku Raincheck',
'Silly Fellows',
'Enduko Emo',
'Masakkali',
'Sailaja Reddy Alludu',
'U Turn',
'Anu Vamsi Katha',
'Karma Kartha Kriya',
'Ishtangaa',
'Taxiwaala',
'My Dear Marthandam',
'Pacific Rim Uprising',
'Rajaratham',
'Kaasi',
'Dr. Satyamurthy',
'Kaala',
'Dammunte Sommera',
'Incredibles 2',
'Tik Tik Tik',
'Chinna Babu',
'Vishwaroopam 2',
'Roshagadu',
'Samudra Puthrudu Aquaman',
'Bhairava Geetha',
'Geetha Govindam',
'U - kathe hero',
'Manchukurisevelalo',
'Idam Jagath',
'Bluff Master',
'Sarabha',
'24 Kisses',
'LAW',
'Rangu',
'Rule',
'Sainyam',
'Student Power',
'Amar Akbar Anthony',
'Operation 2019',
'Next Enti?',
'Subhalekha+Lu',
'Subrahmanyapuram',
'Anaganaga O Premakatha',
'Hushaaru',
'Antariksham 9000 KMPH',
'Padi Padi Leche Manasu',
'Kavacham',
'Srinivasa Kalyanam',
'Mahanati',
'Siva Kasipuram',
'Chalte Chalte',
'Hyderabad Love Story',
'Juvva',
'Raa Raa',
'Ye Mantram Vesave',
'Aithe 2.0',
'Kirrak Party',
'Nelluri Pedda Reddy',
'Vadena',
'Manasainodu',
'Anaganaga Oka Vullo',
'MLA',
'Needi Naadi Oke Katha',
'Rangasthalam',
'Chal Mohan Ranga',
'Soda Golisoda',
'Satya Gang',
'Rachayitha',
'Idi Naa Love Story',
'Tharuvatha Evaru',
'Chilkur Balaji',
'Agnyaathavaasi',
'Jai Simha',
'Rangula Ratnam',
'3 Mukhi',
'Ego',
'Bhaagamathie',
'Chalo',
'HBD - Hacked By Devil',
'Touch Chesi Chudu',
'Howrah Bridge',
'Gayatri',
'Inttelligent',
'Tholi Prema',
'Awe',
'Ameerpet 2 America',
'Manasuku Nachindi',
'Mercury',
'Pantham',
'Aghora',
'Divya Mani',
'Tej I Love You',
'RX 100 (film)',
'Aatagadharaa Siva',
"LoverÂ¿'",
'Wife of Ram',
'Saakshyam',
'Happy Wedding',
'Brand Babu',
'Chi La Sow',
'Devi Vigraham',
'Krishnarjuna Yuddham',
'Goodachari',
'Shambho Shankara',
'Sanjeevani',
'Vijetha',
'Mehbooba',
'Ee Nagariniki Emaindi',
'Kanam',
'Endaro Mahanubhavulu',
'Junction Lo Jayamalini',
'Naa Peru Surya, Naa Illu India',
'Annadata Sukhibhava',
'Seenugadi Prema',
'Bharat Ane Nenu',
'Nela Ticket',
'Ammamma Gari Illu',
'Officer',
'Raju Gadu',
'Best Lovers',
'Naa... Nuvve',
'Sammohanam',
'Jamba Lakidi Pamba',
'Achari America Yatra',
'Sarovaram',
'Raahu',
'Tholubommalata',
'Operation Gold Fish',
'Thupaki Ramudu',
'Malli Malli Chusa',
'Raju Gari Gadhi 3',
'Vanavasam',
'Ragala 24 Gantallo',
'Dandupalyam 4',
'Meeku Maathrame Cheptha',
'Planning',
'Thipparaa Meesam',
'Tenali Ramakrishna BA. BL',
'George Reddy',
'Krishna Rao Supermarket',
'Aaviri',
'RDX Love',
'Ranarangam',
'Oorantha Anukuntunnaru',
'Pichhodu',
'Kobbari Matta',
'Evaru',
'Boy',
'Edaina Jaragocchu',
'Kousalya Krishnamurthy',
'Nene Kedi No.1',
'Saaho',
'Evvarikee Cheppoddu',
'Jodi',
'Gaddalakonda Ganesh',
'Nenu Naa Nagarjuna',
'Pandugadi Photo Studio',
'Rama Chakkani Seetha',
'Rayalaseema Love Story',
'Ninnu Thalachi',
'Sye Raa Narasimha Reddy',
'Chanakya',
'Gang Leader',
'Beach Road Chetan',
'Mr. KK',
'Ranasthalam',
'Puli Joodham',
'Sahasaputrudu',
'The Curse of the Weeping Woman',
'Kanchana 3',
'Tulasi Krishna',
'Evadu Thakkuva Kaadu',
'Nagakanya',
'Lisaa',
'X-Men: Dark Phoenix',
'URI - The Surgical Strike',
'I Love You',
'The Lion King',
'Manmadhudu 2',
'Ayogya',
'Rambo: Last Blood',
'Khaidi',
'Vijay Sethupathi',
'Love Game',
'Captain Marvel',
'Sarvam Thaala Mayam',
'Lovers Day',
'Arjun Suravaram',
'Raja Vaaru Rani Gaaru',
'Raghupathi Venkaiah Naidu',
'Miss Match',
'Bhagyanagara Veedhullo Gammathu',
'Ashwamedham',
'90 ML',
'Amma Rajyam Lo Kadapa Biddalu',
'Traap',
'Venky Mama',
'Prati Roju Pandage',
'Iddari Lokam Okate',
'Mathu Vadalara',
'Software Sudheer',
'Lady Tiger',
'Ranarangam',
'Amavasya',
'Vicharana',
'Ruler',
'Kathanam',
'ABCD â€“ American Born Confused Desi',
'Guna 369',
'Bilalpur Police Station',
'College Poragallu',
'Jessie',
'Magnet',
'Manasa Vaacha',
'Pranam Khareedu',
'Where Is The Venkatalakshmi',
'Prematho Cheppana',
'Adhrushyam',
'Cheddi Gang',
'Chikati Gadilo Chithakotudu',
'Vinara Sodara Veera Kumara',
"Lakshmi's NTR",
'Suryakantham',
'Majili',
'Prema Katha Chitram 2',
'Chitralahari',
'Ashok Reddy',
'Runam',
'Aa Nimisham',
'Prementha Panichese Narayana',
'Dabangg 3',
'Ajay Passayyadu',
'Natana',
'N.T.R: Kathanayakudu',
'Vinaya Vidheya Rama',
'F2 â€“ Fun and Frustration',
'Kothaga Maa Prayanam',
'Mr. Majnu',
'Akkadokaduntadu',
'Bichagada Majaka',
'Gamer',
'Sakala Kala Vallabhudu',
'Nuvvu Thopu Raa',
'Yatra',
'4 Letters',
'Mithai',
'N.T.R: Mahanayakudu',
'Akkadokaduntadu',
'Jersey',
'Danger Love Story',
'Diksoochi',
'Brochevarevarura',
'Captain Rana Prathap',
'Kalki',
'Prema Janta',
'Burrakatha',
'KakatheeyByudu',
'Oh! Baby',
'Durmargudu',
'Dorasani',
'KS100',
'Ninu Veedani Needanu Nene',
'Marketlo Prajaswamyam',
'Rajdhoot',
'iSmart Shankar',
'Dear Comrade',
'Nenu Lenu',
'Bailampudi',
'Voter',
'Special - The Story of a Mind Reader',
'Mallesham',
'Agent Sai Srinivasa Athreya',
'Duppatlo Minnagu',
'Nuvvu Thopu Raa',
'Okate Life',
'Rangu Paduddi',
'Maharshi',
'Enthavaraalaina',
'Romantic Criminals',
'Swayamvadha',
'Rakshasudu',
'Sita',
'31-Dec',
'Falaknuma Das',
'Seven',
'Ek',
'Game Over',
'Vajra Kavachadhara Govinda',
'Viswamitra',
'1st Rank Raju',
'Abhinetri 2',
'April']
  let answer = '';
  let maxWrong = 6;
  let mistakes = 0;
  let guessed = [];
  let wordStatus = null;
  
  function randomWord() {
    answer = tollywood_movies[Math.floor(Math.random() * tollywood_movies.length)];
    answer = answer.toUpperCase();
    // console.log(answer.length);
  }
  
  function generateButtons() {
    let buttonsHTML = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'.split('').map(letter =>
      `
        <button
          class="btn btn-lg btn-secondary m-1"
          id='` + letter + `'
          onClick="handleGuess('` + letter + `')"
        >
          ` + letter + `
        </button>
      `).join('');
  
    document.getElementById('keyboard').innerHTML = buttonsHTML;
  }
  
  function handleGuess(chosenLetter) {
    guessed.indexOf(chosenLetter) === -1 ? guessed.push(chosenLetter) : null;
    document.getElementById(chosenLetter).setAttribute('disabled', true);
  
    if (answer.indexOf(chosenLetter) >= 0) {
      guessedWord();
      checkIfGameWon();
    } else if (answer.indexOf(chosenLetter) === -1) {
      mistakes++;
      updateMistakes();
      checkIfGameLost();
      updateHangmanPicture();
    }
  }
  
  function updateHangmanPicture() {
    document.getElementById('hangmanPic').src = './images/' + mistakes + '.jpg';
  }
  
  function checkIfGameWon() {
    if (wordStatus.length === answer.length) {
      document.getElementById('keyboard').innerHTML = 'You Won!!!';
    }
  }
  
  function checkIfGameLost() {
    if (mistakes === maxWrong) {
      document.getElementById('wordSpotlight').innerHTML = 'The answer was: ' + answer;
      document.getElementById('keyboard').innerHTML = 'You Lost!!!';
    }
  }
  
  function guessedWord() {
    wordStatus = answer.split('').map(letter => (guessed.indexOf(letter) >= 0 ? letter : ((letter == ':')?':':((letter == '.')?'.':((letter == '-')?'-':((letter == ' ')?'\xa0':" _ ")))))).join('');
    // console.log(wordStatus.length);
    document.getElementById('wordSpotlight').innerHTML = wordStatus;
  }
  
  function updateMistakes() {
    document.getElementById('mistakes').innerHTML = mistakes;
  }
  
  function reset() {
    mistakes = 0;
    guessed = [];
    document.getElementById('hangmanPic').src = './images/0.jpg';
  
    randomWord();
    guessedWord();
    updateMistakes();
    generateButtons();
  }
  
  document.getElementById('maxWrong').innerHTML = maxWrong;
  
  randomWord();
  generateButtons();
  guessedWord();
  